update
RuanAragao/calculator pull request #60
Opened 2023-10-22 18:56 UTC by anuamloh07

2023-10-22 19:05 UTC, anuamloh07 commented
Discount calculator feautre whihc can be used in various shopping malls, etc and in daily life as well to get a better idea of the savings

2023-10-23 00:09 UTC, RuanAragao requested changes
**Fix:**
The _Kebab case_ is required for all files and directories. 
Ex.: `./my-directory/my-file.ext`

**Code quality tip:**
All functions, variables and classes always have descriptive, not generic, names. This way it is clearer what the function does.

Exemple:
```javascript
// Bad name
function f1(a, b) {
  const total = a + b;
  return total;
}

// Good name
function sum(a, b) {
  const total = a + b;
  return total;
}
```

2023-10-23 00:09 UTC, RuanAragao commented on index.html
Correct the path. Use slash instead of backslash. ("./calculator/my-calculator/")

2023-10-27 02:47 UTC, RuanAragao approved these changes

2023-10-27 02:47 UTC, RuanAragao commented on index.html
> +  <a href="./calculators/discount-calculator/index.html">Discount Calculator</a>
@anuamloh07 need a `<br />` end of line

2023-10-27 02:47 UTC, RuanAragao commented on index.html
> +  <a href="./calculators/discount-calculator/index.html">Discount Calculator</a>
I added the accepted tag in the PR, but I need you to correct this to do the merge. Thanks!

2023-10-27 02:47 UTC, RuanAragao commented on index.html
> +  <a href="./calculators/discount-calculator/index.html">Discount Calculator</a>
I fix this

2023-10-27 02:47 UTC, merged